[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","C4","SIM","ERA"]
ignore = ["E501"]
target-version = "py310"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"
